import Tag from './defining-component/tag';

/**
 * Do not edit this file. Edit the component file imported above
 */
const tags = {
  engineering: 'green',
  shopping: 'red',
  bananas: 'yellow',
  racing: 'orange',
  refrigeration: 'blue',
};
export default <template>
  <div class="m-4">
    <div class="mb-1">Tags</div>
    {{#each-in tags as |label color|}}
      <Tag @label={{label}} @color={{color}} />
    {{/each-in}}
  </div>
</template>
